import logo from './logo.png'
import HeroBackground from './home.png'
import F1 from './fe1.png'
import F2 from './fe2.png'
import F3 from './fe3.png'
import F4 from './fe4.png'
import F5 from './fe5.png'
import F6 from './fe6.png'
import Footer1 from './footer1.jpg'
import Footer2 from './footer2.png'
import Footer3 from './footer3.jpg'
import AboutPng from './about.jpg'
import Video from './1.mp4'
import P1 from './ppl1.png'
import P2 from './ppl2.png'
import P3 from './ppl3.png'
import Banner1 from './callBanner1.jpg'
import Banner2 from './callBanner2.jpg'
import Banner3 from './textBanner1.jpg'
import Banner4 from './textBanner2.jpg'
import Banner5 from './textBanner3.jpg'
import Blog1 from './blog1.jpg'
import Blog2 from './blog2.jpg'
import Blog3 from './blog3.jpg'
import Blog4 from './blog4.jpg'
import Blog5 from './blog5.jpg'

export {logo, HeroBackground, F1, F2, F3, F4, F5, F6, Footer1, Footer2, Footer3, AboutPng, Video,P1,P2,P3,Banner1,Banner2,Banner3,Banner4,Banner5, Blog1,Blog2,Blog3,Blog4,Blog5}